### ISSUE TITLE
Three major releases in 24 hours.

### ISSUE THREAD

**Issue by phadej** [arrayfire/arrayfire-haskell#31]
Please, sleep over the releases. No need to spam Hackage.

(edit: only three are in rapid succession, the first one is already two days ago...)

**Comment by dmjio** [comment]
@phadej the public interface is changing, a major version bump is required to abide by PVP. Surely hackage can handle 3 POST requests.

**Comment by dmjio** [comment]
@phadej, amazonka uploads 60 packages at a time, I think we're ok here.

**Comment by phadej** [comment]
Hackage is permanent store, it’s one upload but the version is there forever.

You can only upload a package version once and this cannot be undone, so try to get it right the first time! 

You could have made only single major release instead of three. Please rethink your release process taking unique Hackage coat model into account.

**Comment by phadej** [comment]
Amazonka maintainers are not uploading new versions of the same package in short time.

**Comment by dmjio** [comment]
Thanks for the recommendation.

**Comment by dmjio** [comment]
@phadej Also, I noticed when I try to upload the documentation standalone that it doesn't work. Hackage will fail to build this package because it doesn't have the third party libraries, so I have to upload the docs manually. 

Maybe this is what you're referring to ? I'm trying to upload docs here.
```
cabal upload -d arrayfire-0.4.0.0-docs.tar.gz --publish
```

But yes, if there's any way you guys can fix hackage to allow documentation pushes, that would be great. It did work for 0.2.0.0 though. Not sure what's happening now. But how I release packages publicly shouldn't be dictated by hackages data store. Hackage also has a deprecation option as well for that, if need be.

**Comment by phadej** [comment]
Try with web interface https://hackage.haskell.org/package/arrayfire-0.4.0.0/maintain/docs, it works but `cabal` doesn't it's a bug in `cabal-install`. Please report it to its issue tracker.

**Comment by dmjio** [comment]
The granularity of the changes that are batched into a release can be debated, but I'd leave that to the package author's discretion, who should take into account end user's timeline for the needed feature.

**Comment by dmjio** [comment]
Thanks, will give the web API a go.

**Comment by phadej** [comment]
I hope that the end users will donate to Haskell.org which resources are used to host `hackage.haskell.org`

**Comment by dmjio** [comment]
![image](https://user-images.githubusercontent.com/875324/68334464-ae7aa380-00a8-11ea-8976-5a4ae788926a.png)

@phadej So I was able to use the web API to upload documentation, but it doesn't seem to show up on the hackage page. Is there a way I can see any kind of logs as to what the issue might be?

**Comment by dmjio** [comment]
@phadej was able to get haddocks uploaded thanks to @cocreature. For all further PSA (public service announcements) regarding hackage and its cost model, I think this would be better served as a haskell-cafe message so it can benefit the entire community since it seems everybody is at risk. Going forward let's keep this public issue tracker related to ArrayFire issues only. Thanks!
